// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace bolsaemp {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Button submit;
		
		protected System.Web.UI.WebControls.LinkButton image1;
		
		protected System.Web.UI.WebControls.LinkButton image2;
		
		protected System.Web.UI.WebControls.LinkButton image3;
		
		protected System.Web.UI.WebControls.LinkButton image4;
	}
}
