// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class Fing {
	
	protected bolsaemp.pagehead head;
	
	protected bolsaemp.Header Header;
	
	protected System.Web.UI.WebControls.ContentPlaceHolder Main;
	
	protected bolsaemp.TopArea TopArea;
	
	protected bolsaemp.LeftArea LeftArea;
	
	protected bolsaemp.RightArea RightArea;
	
	protected bolsaemp.Footer Footer;
}
